name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          service_account_key: '${{ secrets.GCP_SA_KEY }}'
          export_default_credentials: true

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker

      - name: Build and push backend Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest ./
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest ./react_frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
